version: '3'
services:
  databases:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
  web:
     image: httpd
     ports:
     - "2000:80"
